import { setAlphaUse } from '../js/analysis.js';
import { computeZones, sessionTargets, weeklyPlan, lt2Structure, isRecoveryWeek, sessionMetrics, assessRecent, sessionSummaryText, claudeSummary, parseCalendar, planContext, mondayOf, PLAN_WHY } from '../js/prescribe.js';
let failures = 0; const check = (n, c, d = '') => { console.log((c ? 'PASS ' : 'FAIL ') + n + (d ? '  ' + d : '')); if (!c) failures++; };
const zones = computeZones({ lt1Hr: 146, lt2Hr: 167, lt1Speed: 9.9, lt2Speed: 12.0, maxHr: 188 });
check('zones computed', zones && zones.five.length === 5 && zones.three.length === 3);
check('five-zone boundaries contiguous', zones.five.every((z, i) => i === 0 || z.hrLo === zones.five[i - 1].hrHi + 1), zones.five.map(z => `${z.hrLo}-${z.hrHi}`).join(' '));
const t1 = sessionTargets(zones, 'lt1'); check('LT1 target band 136–143', t1.hrLo === 136 && t1.hrHi === 143 && t1.alphaMin === 0.75, JSON.stringify(t1));
const t2 = sessionTargets(zones, 'lt2'); check('LT2 target band 164–170', t2.hrLo === 164 && t2.hrHi === 170, JSON.stringify(t2));
for (const w of [1, 2, 3, 4, 5, 6, 7, 8, 9]) { const p = weeklyPlan({ zones, week: w, weekdayMin: 60, weekendMin: 150, goal: 'base' }); console.log(`week ${w}${p.recovery ? ' (rec)' : ''}: total ${p.totalMin} min, hard ${p.hardPct}%, long ${p.days[5].minutes} min, tue ${p.days[1].en}`); }
const p1 = weeklyPlan({ zones, week: 1, weekdayMin: 60, weekendMin: 150 });
check('week 1 has one LT2 day and six LT1-type days', p1.days.filter(d => d.type === 'lt2').length === 1 && p1.days.length === 7);
// v1.1.18: the Oct 10 structure — Tue hard, Thu check, Sat long run from 70, Fri optional 30, evenings
check('Tuesday is the one hard day (LT2 ladder 4×8 at MLSS speed)', p1.days.find(d => d.day === 2).type === 'lt2' && /4×8/.test(p1.days.find(d => d.day === 2).en) && /strength A/.test(p1.days.find(d => d.day === 2).evening.en), p1.days.find(d => d.day === 2).en);
check('Mon and Wed are easy runs of 50 min with the speed band as the dose', [1, 3].every(dd => { const d = p1.days.find(x => x.day === dd); return d.type === 'lt1' && d.minutes === 50 && Array.isArray(d.speed) && /speed is the dose/.test(d.note.en); }));
check('Thursday is the two-lap check, Friday an optional 30, Sunday easy 50 with the optional incline walk', p1.days.find(d => d.day === 4).type === 'verify' && p1.days.find(d => d.day === 5).optional === true && p1.days.find(d => d.day === 5).minutes === 30 && p1.days.find(d => d.day === 0).minutes === 50 && /incline walk/.test(p1.days.find(d => d.day === 0).evening.en));
check('the long run starts at 70 and grows +10 a week to 100', [1, 2, 3, 4, 5, 6].map(w => weeklyPlan({ zones, week: w, blockWeek: w }).days.find(d => d.day === 6).minutes).join() === '70,80,90,70,100,100', [1, 2, 3, 4, 5, 6].map(w => weeklyPlan({ zones, week: w, blockWeek: w }).days.find(d => d.day === 6).minutes).join());
check('block week and ladder week are separate: block week 9 with ladder week 1 → long run 100, ladder 4×8', (() => { const p = weeklyPlan({ zones, week: 1, blockWeek: 9 }); return p.days.find(d => d.day === 6).minutes === 100 && /4×8/.test(p.days.find(d => d.day === 2).en); })());
check('an MLSS week puts the 30-min MLSS check on Tuesday (verify mode, purpose mlss, LT2 speed)', (() => { const d = weeklyPlan({ zones, week: 1, kinds: ['mlss'] }).days.find(x => x.day === 2); return d.type === 'verify' && d.purpose === 'mlss' && d.speed === 12 && /0\.5–1\.0 → that speed is the MLSS/.test(d.note.en); })());
check('a blood week: Tuesday easy with the note, Thursday no run, strength at RPE 7', (() => { const p = weeklyPlan({ zones, week: 2, kinds: ['blood'], notes: ['blood test Thu 07:00'] }); const tue = p.days.find(x => x.day === 2), thu = p.days.find(x => x.day === 4); return tue.type === 'lt1' && /blood test Thu/.test(tue.note.en) && thu.type === 'rest' && thu.minutes === 0 && /RPE 7/.test(thu.evening.en) && p.light; })());
check('a step week replaces the long run with the step test', (() => { const d = weeklyPlan({ zones, week: 2, kinds: ['step'] }).days.find(x => x.day === 6); return d.type === 'test' && /instead of the long run/.test(d.note.en); })());
check('a recovery kind makes the week a recovery week (Tuesday easy, long run × 0.7)', (() => { const p = weeklyPlan({ zones, week: 2, blockWeek: 4, kinds: ['recovery'] }); return p.recovery && p.days.find(x => x.day === 2).type === 'lt1' && p.days.find(x => x.day === 6).minutes === 70; })());
check('mondayOf: 2026-10-10 (Sat) → 2026-10-05, 2026-10-12 (Mon) → itself', mondayOf('2026-10-10') === '2026-10-05' && mondayOf('2026-10-12') === '2026-10-12');
const cal = parseCalendar('2026-10-12 recovery after the test\n2026-10-20 mlss MLSS check\n# comment\n2026-10-31 step step test 60\n2026-11-12 blood blood test\nnonsense line\n2026-11-13 foo unknown kind');
check('parseCalendar: dates round to Mondays, unknown kinds and bad lines are ignored, notes kept', Object.keys(cal).sort().join() === '2026-10-12,2026-10-19,2026-10-26,2026-11-09' && cal['2026-10-19'].kinds[0] === 'mlss' && cal['2026-10-26'].kinds.includes('step') && cal['2026-11-09'].notes[0] === 'blood test', JSON.stringify(cal));
const ctx = d => planContext({ startDate: '2026-10-12', calendar: cal, now: new Date(d + 'T12:00:00') });
check('planContext: block weeks count every week, ladder weeks skip recovery/mlss/blood weeks', ctx('2026-10-14').blockWeek === 1 && ctx('2026-10-14').ladderWeek === 1 && ctx('2026-10-14').kinds.includes('recovery') && ctx('2026-10-21').kinds.includes('mlss') && ctx('2026-10-27').ladderWeek === 1 && ctx('2026-10-27').blockWeek === 3 && ctx('2026-10-27').kinds.includes('step') && ctx('2026-11-03').ladderWeek === 2 && ctx('2026-11-10').kinds.includes('blood') && ctx('2026-11-17').ladderWeek === 3 && ctx('2026-11-24').ladderWeek === 4 && ctx('2026-12-01').ladderWeek === 5 && ctx('2026-12-08').ladderWeek === 6, JSON.stringify(['2026-10-14', '2026-10-21', '2026-10-27', '2026-11-03', '2026-11-10', '2026-11-17', '2026-11-24', '2026-12-01', '2026-12-08'].map(d => [d, ctx(d).blockWeek, ctx(d).ladderWeek, ctx(d).kinds.join('+')])));
check('planContext: the long run does not grow across a step-test week (longWeek)', ctx('2026-10-21').longWeek === 2 && ctx('2026-10-27').longWeek === 2 && ctx('2026-11-03').longWeek === 3 && ctx('2026-11-10').longWeek === 4 && (() => { const c = ctx('2026-11-03'); return weeklyPlan({ zones, week: c.ladderWeek, blockWeek: c.blockWeek, longWeek: c.longWeek, kinds: c.kinds }).days[5].minutes === 90; })(), JSON.stringify(['2026-10-21', '2026-10-27', '2026-11-03', '2026-11-10'].map(d => ctx(d).longWeek)));
check('planContext before the start date: week 1, no kinds; weekOffset moves the week', ctx('2026-10-03').blockWeek === 1 && ctx('2026-10-03').ladderWeek === 1 && planContext({ startDate: '2026-10-12', calendar: cal, now: new Date('2026-10-14T12:00:00'), weekOffset: 1 }).kinds.includes('mlss'));
check('the whole calendar through the plan: 10/27 ladder 4×8 + step Saturday; 11/24 recovery; 12/8 2×20', (() => { const run = d => { const c = ctx(d); return weeklyPlan({ zones, week: c.ladderWeek, blockWeek: c.blockWeek, kinds: c.kinds, notes: c.notes }); }; const a = run('2026-10-27'), b = run('2026-11-24'), c = run('2026-12-08'), m = run('2026-10-20'); return /4×8/.test(a.days[1].en) && a.days[5].type === 'test' && b.recovery && b.days[1].type === 'lt1' && /2×20/.test(c.days[1].en) && m.days[1].purpose === 'mlss'; })());
check('planContext survives an unreadable start date (falls back to this week)', (() => { const c = planContext({ startDate: 'garbage', calendar: '', now: new Date('2026-10-14T12:00:00') }); return c.blockWeek === 1 && c.ladderWeek === 1 && c.longWeek === 1 && c.monday === '2026-10-12'; })());
check('PLAN_WHY carries the rationale in both languages', PLAN_WHY.length >= 6 && PLAN_WHY.every(w => w.ko && w.en) && PLAN_WHY.some(w => /Stanley 2013/.test(w.en)));
check('weekday sessions fit 60 min', p1.days.filter(d => [1, 2, 4, 5].includes(d.day)).every(d => d.minutes <= 60));
check('hard share ≤ 25%', p1.hardPct <= 25, p1.hardPct + '%');
check('recovery week 4 has no LT2', weeklyPlan({ zones, week: 4 }).days.every(d => d.type !== 'lt2') && isRecoveryWeek(4));
check('LT2 progression 4×8 → 4×10 → 5×10', lt2Structure(1).reps === 4 && lt2Structure(1).workSec === 480 && lt2Structure(2).workSec === 600 && lt2Structure(3).reps === 5);
// metrics + insights on fake sessions
const now = Date.now();
const fakeSession = (a1, drift, daysAgo) => { const hr = []; for (let i = 0; i < 3000; i++) hr.push([now - daysAgo * 86400000 + i * 1000, 138 + (i / 3000) * drift]); return { type: 'lt1', final: true, startedAt: now - daysAgo * 86400000, endedAt: now - daysAgo * 86400000 + 3000000, hrLive: hr, features: Array.from({ length: 500 }, (_, i) => ({ t: 0, alpha1: a1, phase: 'work', artifactPct: 1 })), tiz: { inSec: 2400, totalSec: 3000 }, rr: [] }; };
const m = sessionMetrics(fakeSession(0.65, 10, 1)); check('metrics drift ≈ +4.2% (first 5 min excluded)', Math.abs(m.driftPct - 4.15) < 0.3, m.driftPct.toFixed(2));
const ins = assessRecent([fakeSession(0.65, 2, 1), fakeSession(0.66, 1, 3)], zones, now - 70 * 86400000);
check('low α1 → −3 bpm adjust', ins.lt1Adjust === -3, JSON.stringify(ins.notes.map(n => n.en)));
check('retest flagged at 10 weeks', ins.retest === true);
const insDemo = assessRecent([{ ...fakeSession(0.65, 2, 1), sourceKind: 'demo' }, { ...fakeSession(0.66, 1, 3), sourceKind: 'demo' }], zones, now - 7 * 86400000);
check('practice sessions on the demo strap never adjust the real targets', insDemo.lt1Adjust === 0 && insDemo.sessionsConsidered === 0, JSON.stringify(insDemo.notes.map(n => n.en)));
const txt = sessionSummaryText(fakeSession(0.65, 2, 1), m, zones); check('summary text bilingual', /LT1보다 높은/.test(txt.ko) && /Harder than LT1/.test(txt.en));
const cs = claudeSummary({ profile: { age: 29, restHr: 52, maxHr: 188 }, zones: { ...zones, grade: 'B' }, session: fakeSession(0.8, 1, 0), metrics: m, plan: p1 });
check('claude summary has sections', /Thresholds/.test(cs) && /Plan week 1/.test(cs));
// α1 guidance switched off (Settings → α1, default since v1.1.14): no target change, no α1 verdict, the summary says to ignore α1
setAlphaUse(false);
const insOff = assessRecent([fakeSession(0.65, 2, 1), fakeSession(0.66, 1, 3)], zones, now - 70 * 86400000);
check('α1 off: low α1 no longer lowers the LT1 target', insOff.lt1Adjust === 0 && !insOff.notes.some(n => /α1/.test(n.en)), JSON.stringify(insOff.notes.map(n => n.en)));
const txtOff = sessionSummaryText(fakeSession(0.65, 2, 1), m, zones);
check('α1 off: no α1 line or "harder than LT1" verdict in the session text', !/α1/.test(txtOff.ko + txtOff.en) && !/Harder than LT1/.test(txtOff.en), txtOff.en);
const csOff = claudeSummary({ profile: { age: 29, restHr: 52, maxHr: 188 }, zones: { ...zones, grade: 'B' }, session: fakeSession(0.8, 1, 0), metrics: m, plan: p1 });
check('α1 off: the copied summary keeps the α1 numbers but says not to use them', /mean α1/.test(csOff) && /switched OFF/.test(csOff));
setAlphaUse(true);
console.log(failures ? `\n${failures} FAILURE(S)` : '\nALL PASS'); process.exit(failures ? 1 : 0);
