// node test/test_session.mjs — full synthetic step test through the engine at ×120, then analysis
import { SessionEngine } from '../js/session.js';
import { DemoSource, demoProfileForEngine } from '../js/sources.js';
import { analyzeSession } from '../js/analysis.js';
let failures = 0; const check = (n, c, d = '') => { console.log((c ? 'PASS ' : 'FAIL ') + n + (d ? '  ' + d : '')); if (!c) failures++; };
const settings = { protocol: { warmupSec: 120, stageSec: 180, pauseSec: 30, startSpeed: 6, speedStep: 1, incline: 1, type: 'speed', stopLactate: 6, stopRpe: 17, warmupSpeed: 5.5, maxStages: 12 }, treadmill: { maxSpeed: 18, maxIncline: 15 }, alpha1: { artifactMode: 'auto', windowSec: 120, stepSec: 5, lambda: 500 }, alerts: { zoneExitSec: 30 } };
const spoken = []; const alerts = { speak: (t) => spoken.push(t), cue: (t) => spoken.push(t), keepAwake: async () => true, beep() {}, vibrate() {} };
const laTruth = s => +(0.9 + 0.08 * Math.exp(0.55 * (s - 8))).toFixed(1);
const engine = new SessionEngine({ settings, alerts, onEvent: (e) => { if (e.type === 'lactate-prompt') { const st = engine.stages.find(s => s.idx === e.stage); setTimeout(() => engine.enterLactate(laTruth(st.speed), e.stage), 50); } } });
engine.configure({ mode: 'test' });
const src = new DemoSource({ speed: 120, profile: demoProfileForEngine(engine) });
engine.setSource(src);
await src.connect();
engine.start();
const t0 = Date.now();
await new Promise(res => { const h = setInterval(() => { const v = engine.view(); if (v.phase === 'done' || v.stopAdvised && v.phase === 'pause' || engine.state !== 'running' || Date.now() - t0 > 60000) { clearInterval(h); res(); } }, 200); });
const session = engine.stop('test-done'); await src.disconnect();
console.log('wall', ((Date.now() - t0) / 1000).toFixed(1), 's; data', (session.endedAt - session.startedAt) / 1000, 's; stages', session.stages.length, 'features', session.features.length, 'rr', session.rr.length);
check('≥7 stages completed', session.stages.length >= 7, String(session.stages.length));
check('lactate recorded for stages', session.stages.filter(s => s.lactate != null).length >= 6);
check('stop advised once lactate ≥ 6', session.stages.some(s => s.lactate >= 6) ? spoken.some(t => /종료 기준/.test(t)) : true);
check('voice prompts issued (stage start/end)', spoken.some(t => /1단계/.test(t)) && spoken.some(t => /채혈/.test(t)));
const art = session.rr.filter(r => r[2] === 0).length / session.rr.length * 100;
check('artifact rate low in demo (<3%)', art < 3, art.toFixed(2) + '%');
const r = analyzeSession(session);
console.log(r.rows.map(x => `${x.speed}:${x.hr.toFixed(0)}bpm a1=${isFinite(x.alpha1) ? x.alpha1.toFixed(2) : '-'} la=${x.lactate}`).join(' | '));
check('HRVT1 found near 11 km/h (±1)', r.hrv.hrvt1 && Math.abs(r.hrv.hrvt1.speed - 11) <= 1.0, JSON.stringify(r.hrv.hrvt1));
check('LT1 lactate found', r.lactate && isFinite(r.lactate.lt1Primary.x), `${r.lactate?.lt1Primary.x?.toFixed(2)} km/h`);
check('LT2 lactate found', r.lactate && isFinite(r.lactate.lt2Primary.x), `${r.lactate?.lt2Primary.x?.toFixed(2)} km/h hr ${r.lactate?.lt2Primary.hr?.toFixed(0)}`);
check('triangulation produced', r.tri.lt1 && r.tri.lt2, `${r.tri.grade1}/${r.tri.grade2}`);
console.log(failures ? `\n${failures} FAILURE(S)` : '\nALL PASS'); process.exit(failures ? 1 : 0);
